# Site
name: "ventaubain"
title: "ventaubain (WEBSITE EN COURS DE CREATION - NON STABLE)"
description: "Des tutos pour mieux comprendre l'IA, Kubernetes et le monde du Cloud !"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: ''
disqus:
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ventaubain:
    name: ventaubain
    display_name: ventaubain
    gravatar:
    email:
    web:
    twitter:
    description: "Auteur"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
